# Generated by Django 3.1.7 on 2021-03-18 04:58

import coaches.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=coaches.models.upload_location)),
                ('gender', models.CharField(max_length=1)),
                ('focus_health', models.BooleanField(default=False)),
                ('focus_wellness', models.BooleanField(default=False)),
                ('focus_health_wellness', models.BooleanField(default=False)),
                ('focus_holistic', models.BooleanField(default=False)),
                ('focus_life', models.BooleanField(default=False)),
                ('focus_behavioral', models.BooleanField(default=False)),
                ('travel', models.BooleanField()),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
