# Generated by Django 3.1.7 on 2021-03-18 05:03

import coaches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='city',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='location',
        ),
        migrations.AlterField(
            model_name='coach',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=coaches.models.upload_location),
        ),
    ]
